---
kind: Template
apiVersion: v1
metadata:
  name: prometheus
  annotations:
    "openshift.io/display-name": Prometheus
    description: |
      Prometheus server.
    iconClass: fa fa-cogs
    tags: "metrics,monitoring,prometheus"
parameters:
- description: The location of the grafana image
  name: IMAGE_PROMETHEUS
  value: docker.io/prom/prometheus:v2.9.2
- description: External URL for the prometheus route
  name: ROUTE_URL
  value: ""
- description: The namespace to instantiate heapster under. Defaults to 'namespace'.
  name: NAMESPACE
  value: namespace
- description: The environment to instantiate heapster under. Defaults to 'environment'.
  name: ENVIRONMENT
  value: environment
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
    
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: prometheus
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
  spec:
    host: "${ROUTE_URL}"
    to:
      name: prometheus
      kind: Service
      weight: 100
    tls:
      termination: edge
- apiVersion: v1
  kind: Service
  metadata:
    name: prometheus
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/scheme: http
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
    labels:
      metrics-infra: prometheus
      name: prometheus
  spec:
    ports:
    - name: prometheus
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      app: prometheus
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: prometheus
    name: prometheus
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: prometheus
    template:
      metadata:
        labels:
          app: prometheus
        name: prometheus
      spec:
        serviceAccountName: prometheus
        containers:
        - args:
            - '--volume-dir=/etc/config'
            - '--webhook-url=http://127.0.0.1:9090/-/reload'
          image: 'jimmidyson/configmap-reload:v0.2.2'
          imagePullPolicy: IfNotPresent
          name: prometheus-prometheus-service-configmap-reload
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: TZ
              value: "America/Vancouver"
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
              readOnly: true
        - args:
            - '--config.file=/etc/config/prometheus.yml'
            - '--storage.tsdb.path=/data'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
          image: '${IMAGE_PROMETHEUS}'
          env:
            - name: TZ
              value: "America/Vancouver"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: prometheus-prometheus-service
          ports:
            - containerPort: 9090
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
            - mountPath: /data
              name: prometheus-data
        volumes:
         - configMap:
            defaultMode: 420
            name: prometheus-service
           name: config-volume
         - name: prometheus-data
           persistentVolumeClaim:
              claimName: prometheus-service
              
- apiVersion: v1
  kind: "PersistentVolumeClaim"
  metadata:
    name: "prometheus-service"
  spec:
     storageClassName: netapp-block-standard
     accessModes:
      - ReadWriteOnce
     resources:
       requests:
         storage: 5Gi
  volumeName: "prometheus-service"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: prometheus-service
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
  data:
     alerts: |
       {}
     prometheus.rules: |
       groups:
       - name: example-rules
         interval: 30s # defaults to global interval
         rules:
         - alert: "Node Down"
           expr: up{job="kubernetes-nodes"} == 0
           annotations:
             miqTarget: "ContainerNode"
             severity: "ERROR"
             url: "https://www.example.com/node_down_fixing_instructions"
             message: "Node {{$labels.instance}} is down"
         - alert: "Too Many Pods"
           expr: sum(kubelet_running_pod_count) > 15
           annotations:
             miqTarget: "ExtManagementSystem"  
             severity: "ERROR"
             url: "https://www.example.com/too_many_pods_fixing_instructions"
             message: "Too many running pods"
         - alert: "Node CPU Usage"
           expr: (100 - (avg by (instance) (irate(node_cpu{app="prometheus-node-exporter",mode="idle"}[5m])) * 100)) > 3
           for: 30s
           labels:
             severity: "ERROR"
           annotations:
             miqTarget: "ExtManagementSystem"
             severity: "ERROR"
             url: "https://www.example.com/too_many_pods_fixing_instructions"
             message: "{{$labels.instance}}: CPU usage is above 4% (current value is: {{ $value }})"
     prometheus.yml: |
       global:
         evaluation_interval: 1m
         scrape_interval: 1m
         scrape_timeout: 10s
       rule_files:
       - /etc/config/rules
       - /etc/config/alerts
       scrape_configs:
       - job_name: blackbox
         metrics_path: /probe
         params:
           module: [http_2xx]
         static_configs:
           - targets:
             - https://digitalid-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - http://grafana-${NAMESPACE}-tools.pathfinder.gov.bc.ca
             - https://pen-demographics-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - https://pen-request-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - https://pen-request-email-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - https://pen-request-${NAMESPACE}-dev.pathfinder.gov.bc.ca/api
             - https://pen-request-${NAMESPACE}-dev.pathfinder.gov.bc.ca
             - https://services-card-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - https://soam-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - https://${NAMESPACE}-dev.pathfinder.gov.bc.ca
             - https://student-admin-${NAMESPACE}-dev.pathfinder.gov.bc.ca/api/health
             - https://student-admin-${NAMESPACE}-dev.pathfinder.gov.bc.ca
             - https://student-api-${NAMESPACE}-dev.pathfinder.gov.bc.ca/health
             - https://digitalid-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://pen-demographics-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://pen-request-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://pen-request-email-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://pen-request-${NAMESPACE}-test.pathfinder.gov.bc.ca/api
             - https://pen-request-${NAMESPACE}-test.pathfinder.gov.bc.ca
             - https://services-card-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://soam-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://${NAMESPACE}-test.pathfinder.gov.bc.ca
             - https://student-admin-${NAMESPACE}-test.pathfinder.gov.bc.ca/api/health
             - https://student-admin-${NAMESPACE}-test.pathfinder.gov.bc.ca
             - https://student-api-${NAMESPACE}-test.pathfinder.gov.bc.ca/health
             - https://digitalid-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://pen-demographics-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://pen-request-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://pen-request-email-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://getmypen.gov.bc.ca/api
             - https://getmypen.gov.bc.ca
             - https://services-card-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://soam-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://${NAMESPACE}.pathfinder.gov.bc.ca
             - https://student-admin-${NAMESPACE}-prod.pathfinder.gov.bc.ca/api/health
             - https://student-admin-${NAMESPACE}-prod.pathfinder.gov.bc.ca
             - https://student-api-${NAMESPACE}-prod.pathfinder.gov.bc.ca/health
             - https://sonarqube-${NAMESPACE}-tools.pathfinder.gov.bc.ca
             - https://jenkins-${NAMESPACE}-tools.pathfinder.gov.bc.ca/login
         relabel_configs:
           - source_labels: [__address__]
             target_label: __param_target
           - source_labels: [__param_target]
             target_label: instance
           - target_label: __address__
             replacement: blackbox-${NAMESPACE}-tools.pathfinder.gov.bc.ca # Blackbox exporter.
       - job_name: prometheus
         static_configs:
         - targets:
           - localhost:9090
       - job_name: redis_exporter
         scrape_timeout: 30s
         static_configs:
         - targets:
           - redis-exporter-c2mvws-dev.pathfinder.gov.bc.ca
           - redis-exporter-c2mvws-test.pathfinder.gov.bc.ca
           - redis-exporter-c2mvws-prod.pathfinder.gov.bc.caa
       - job_name: kubernetes-pods
         metrics_path: /actuator/prometheus
         kubernetes_sd_configs:
         - role: pod
           namespaces:
             names:
               - ${NAMESPACE}-tools
         relabel_configs:
         - action: keep
           regex: true
           source_labels:
           - __meta_kubernetes_pod_annotation_prometheus_io_scrape
         - action: replace
           regex: (.+)
           source_labels:
           - __meta_kubernetes_pod_annotation_prometheus_io_path
           target_label: __metrics_path__
         - action: replace
           regex: ([^:]+)(?::\d+)?;(\d+)
           replacement: $1:$2
           source_labels:
           - __address__
           - __meta_kubernetes_pod_annotation_prometheus_io_port
           target_label: __address__
         - action: labelmap
           regex: __meta_kubernetes_pod_label_(.+)
         - action: replace
           source_labels:
           - __meta_kubernetes_namespace
           target_label: kubernetes_namespace
         - action: replace
           source_labels:
           - __meta_kubernetes_pod_name
           target_label: kubernetes_pod_name
     rules: |
       {}
