{
 "title": "Ministry of Education Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "DEV Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Card API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://services-card-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Digital ID API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://digitalid-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Demographics API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-demographics-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Email API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-email-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Backend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-dev.pathfinder.gov.bc.ca/api\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Frontend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM Keycloak Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Frontend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Backend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-dev.pathfinder.gov.bc.ca/api/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  { "title": "TEST Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Services Card API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://services-card-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Digital ID API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://digitalid-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Demographics API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-demographics-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Email API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-email-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Backend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-test.pathfinder.gov.bc.ca/api\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Frontend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM Keycloak Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Frontend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Backend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-test.pathfinder.gov.bc.ca/api/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  }
 ]
}