{
 "title": "Ministry of Education Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "DEV Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Card API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://services-card-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Digital ID API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://digitalid-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Demographics API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-demographics-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Email API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-email-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Backend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-dev.pathfinder.gov.bc.ca/api\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Frontend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM Keycloak Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Frontend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Backend Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-dev.pathfinder.gov.bc.ca/api/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student API Monitor (DEV)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  { "title": "TEST Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Services Card API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://services-card-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Digital ID API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://digitalid-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Demographics API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-demographics-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Email API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-email-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Backend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-test.pathfinder.gov.bc.ca/api\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request Frontend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM Keycloak Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Frontend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Backend Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-test.pathfinder.gov.bc.ca/api/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student API Monitor (TEST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}"
    }
   ]
  }
 ]
}
{
 "title": "Ministry of Education Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Tools Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://grafana-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Sonarqube",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://sonarqube-<namespace>-tools.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://jenkins-<namespace>-tools.pathfinder.gov.bc.ca/login\",job=\"blackbox\"}*-1"
    }
   ]
  },
  { "title": "DEV Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "PEN Request Backend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-dev.pathfinder.gov.bc.ca/api\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request Frontend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Digital ID",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://digitalid-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request Email API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-email-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Demographics API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-demographics-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Services Card API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://services-card-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "SOAM API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-api-<namespace>-dev.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "SOAM Keycloak",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Admin Backend (Node.js)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-dev.pathfinder.gov.bc.ca/api/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Admin Frontend (Vue.js)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-dev.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  { "title": "TEST Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PEN Request Backend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-test.pathfinder.gov.bc.ca/api\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request Frontend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Digital ID",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://digitalid-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request Email API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-request-email-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Demographics API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://pen-demographics-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Services Card API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://services-card-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "SOAM API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-api-<namespace>-test.pathfinder.gov.bc.ca/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "SOAM Keycloak",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Admin Backend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-test.pathfinder.gov.bc.ca/api/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Admin Frontend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-<namespace>-test.pathfinder.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  }
 ]
}