{
 "title": "Ministry of Education Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "${ENVIRONMENT} Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Card API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://services-card-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Digital ID API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://digitalid-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Request API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://pen-request-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PEN Demographics API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://pen-demographics-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Profile Email API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-profile-email-api-master.${PEN_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Profile Request Backend Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://${ENVIRONMENT}.getmypen.gov.bc.ca/api/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Profile Request Frontend Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://${ENVIRONMENT}.getmypen.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://soam-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SOAM Keycloak Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Frontend Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-${PEN_NAMESPACE}-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student Admin Backend Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-${PEN_NAMESPACE}-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca/api/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Student API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Redis Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_up{instance=\"redis-exporter-${PEN_NAMESPACE}-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca:80\",job=\"redis_exporter\"}"
    }
   ]
  },
  {
   "title": "PROFILE API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-profile-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "PROFILE SAGA API Monitor (${ENVIRONMENT})",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-profile-saga-api-master.${PEN_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}"
    }
   ]
  }
 ]
}
{
 "title": "Ministry of Education Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "${ENVIRONMENT} Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Student Profile Backend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://${ENVIRONMENT}.getmypen.gov.bc.ca/api/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Profile Frontend",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://${ENVIRONMENT}.getmypen.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Digital ID",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://digitalid-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Request API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://pen-request-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PROFILE Request Email API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-profile-email-api-master.${PEN_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PEN Demographics API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://pen-demographics-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "PROFILE API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-profile-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Services Card API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://services-card-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "SOAM API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://soam-api-master.${COMMON_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "SOAM Keycloak",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://soam-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Admin Backend (Node.js)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-${PEN_NAMESPACE}-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca/api/health\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Student Admin Frontend (Vue.js)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://student-admin-${PEN_NAMESPACE}-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca\",job=\"blackbox\"}*-1"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_up{instance=\"redis-exporter-${PEN_NAMESPACE}-${ENVIRONMENT}.apps.silver.devops.gov.bc.ca:80\",job=\"redis_exporter\"}"
    }
   ]
  },
  {
   "title": "PROFILE SAGA API",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://student-profile-saga-api-master.${PEN_NAMESPACE}-${ENVIRONMENT}.svc.cluster.local:8080/actuator/health\",job=\"blackbox\"}*-1"
    }
   ]
  }
 ]
}