---
kind: Template
apiVersion: v1
metadata:
  name: blackbox
  annotations:
    "openshift.io/display-name": Blackbox
    description: |
      Blackbox server.
    iconClass: fa fa-cogs
    tags: "metrics,monitoring,blackbox"
parameters:
- description: The location of the blackbox image
  name: IMAGE_BLACKBOX
  value: docker-remote.artifacts.developer.gov.bc.ca/bitnami/blackbox-exporter:latest
- description: DOMAIN for the app to be hosted.
  name: DOMAIN
  required: true
- description: The namespace to instantiate heapster under. Defaults to 'namespace'.
  name: NAMESPACE
  value: namespace
- description: The environment to instantiate heapster under. Defaults to 'environment'.
  name: ENVIRONMENT
  value: environment
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: blackbox
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
    labels:
      name: blackbox
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: blackbox
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
    labels:
      name: blackbox
  spec:
    host: "blackbox-${NAMESPACE}-${ENVIRONMENT}.${DOMAIN}"
    to:
      name: blackbox
      kind: Service
      weight: 100

- apiVersion: v1
  kind: Service
  metadata:
    name: blackbox
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/scheme: http
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
    labels:
      metrics-infra: blackbox
      name: blackbox
  spec:
    ports:
    - name: blackbox
      port: 9115
      protocol: TCP
      targetPort: 9115
    selector:
      app: blackbox
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: blackbox
    name: blackbox
    namespace: "${NAMESPACE}-${ENVIRONMENT}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: blackbox
    template:
      metadata:
        labels:
          app: blackbox
        name: blackbox
      spec:
        serviceAccountName: blackbox
        containers:
        imagePullSecrets:
          - name: artifactory-creds
        - name: blackbox
          image: ${IMAGE_BLACKBOX}
          env:
            - name: TZ
              value: "America/Vancouver"
          ports:
          - name: blackbox-http
            containerPort: 80
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"

      
